# -*- coding: utf-8 -*-
# Copyright © 2020, VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

strictness: medium
test-warnings: false

pycodestyle:
  full: true
  disable:
    - N802 # pep8-naming: function name should be lower case

pydocstyle:
  run: false

pylint:
  disable:
    - consider-using-f-string
    - global-variable-not-assigned
    - consider-iterating-dictionary
