#!/usr/bin/env python3
'''
Copyright (c) 2017 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: BSD-2-Clause
'''


import argparse
import logging
import os

from report import report
from utils import cache
from utils import constants
'''
Tern executable
'''

# global logger
logger = logging.getLogger(constants.logger_name)
logger.setLevel(logging.DEBUG)

console = logging.StreamHandler()
console.setLevel(logging.DEBUG)
formatter = logging.Formatter(
    '%(asctime)s - %(levelname)s - %(module)s - %(message)s')
console.setFormatter(formatter)

log_handler = logging.FileHandler(constants.logfile, mode='w')
log_handler.setLevel(logging.DEBUG)
log_handler.setFormatter(formatter)

logger.addHandler(console)
logger.addHandler(log_handler)


def main(args):
    '''Execute according to subcommands'''
    logger.debug('Starting...')
    if args.clear_cache:
        logger.debug('Clearing cache...')
        cache.clear()
    if hasattr(args, 'name') and args.name == 'report':
        if args.dockerfile:
            report.execute_dockerfile(args)
        if args.docker_image:
            report.execute_docker_image(args)
        logger.debug('Report completed.')
    logger.debug('Finished')


if __name__ == '__main__':

    def check_file_existence(path):
        if not os.path.isfile(path):
            msg = "{}: does not exist".format(path)
            raise argparse.ArgumentTypeError(msg)
        return path

    parser = argparse.ArgumentParser(
        prog='Tern',
        description='''
           Tern is a container image component curation tool. Tern retrieves
    information about packages that are installed in a container image.
    Learn more at https://github.com/vmware/tern''')
    parser.add_argument('-c', '--clear-cache', action='store_true',
                        help="Clear the cache before running")
    parser.add_argument('-k', '--keep-working-dir', action='store_true',
                        help="Keep the working directory after execution")
    parser.add_argument('-r', '--redo', action='store_true',
                        help="Repopulate the cache for found layers")
    subparsers = parser.add_subparsers(help='Subcommands')
    # subparser for report
    parser_report = subparsers.add_parser('report',
                                          help="Create a report")
    parser_report.add_argument('-d', '--dockerfile', type=check_file_existence,
                               help="Dockerfile used to build the Docker"
                               " image")
    parser_report.add_argument('-i', '--docker-image',
                               help="Docker image that exists locally -"
                               " image:tag")
    parser_report.add_argument('-s', '--summary', action='store_true',
                               help="Summarize the report as a list of"
                               " packages with associated information")
    parser_report.add_argument('-Y', '--yaml-file', action='store_true',
                               help="Create a report in yaml format")
    parser_report.add_argument('-J', '--json-file', action='store_true',
                               help="Create a report in json format")
    parser_report.set_defaults(name='report')
    args = parser.parse_args()

    # execute
    main(args)
