# -*- coding: utf-8 -*-
#
# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause
#
"""
SPDX document formatting
"""

# document level strings
spdx_version = 'SPDXVersion: SPDX-2.1'
data_license = 'DataLicense: CC0-1.0'
spdx_id = 'SPDXID: SPDXRef-DOCUMENT'
document_name = 'DocumentName: Tern report for {image_name}'
document_comment = '''DocumentComment: <text>This document was generated by '''
'''the Tern Project at https://github.com/vmware/tern</text>'''
document_namespace = 'DocumentNamespace: https://spdx.org/spdxdocs/tern'
'-report-{image_id}-{version}'
license_list_version = 'LicenseListVersion: 3.4'
creator = 'Creator: Tool: tern-{version}'
created = 'Created: {timestamp}'
