from spdx_tools.spdx.model import Version

DOCUMENT_ID = 'SPDXRef-DOCUMENT'
DOCUMENT_NAME = 'Tern report for {image_name}'
SPDX_VERSION = 'SPDX-2.2'
DATA_LICENSE = 'CC0-1.0'
DOCUMENT_COMMENT = 'This document was generated by ' \
    'the Tern Project: https://github.com/tern-tools/tern'
DOCUMENT_NAMESPACE = 'https://spdx.org/spdxdocs/tern-' \
    'report-{version}-{image}-{uuid}'
LICENSE_LIST_VERSION = Version(3, 20)
CREATOR_NAME = 'tern-{version}'
DOCUMENT_NAME_SNAPSHOT = 'Tern SPDX SBoM'
DOCUMENT_NAMESPACE_SNAPSHOT = 'https://spdx.org/spdxdocs/tern-report-' \
    '{timestamp}-{uuid}'
